//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int ID { get; set; }
        public string thing1 { get; set; }
        public string thing2 { get; set; }
        public string thing3 { get; set; }
        public string thing4 { get; set; }
    }
}
